name: swdb_2019
channels:
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2019.5.15
  - certifi=2019.6.16
  - cycler=0.10.0
  - freetype=2.9.1
  - intel-openmp=2019.4
  - kiwisolver=1.1.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libpng=1.6.37
  - matplotlib=3.1.0
  - mkl=2019.4
  - mkl-service=2.0.2
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - ncurses=6.1
  - numpy=1.16.4
  - numpy-base=1.16.4
  - openssl=1.1.1c
  - pandas=0.25.0
  - pip=19.1.1
  - pyparsing=2.4.0
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.1
  - readline=7.0
  - scipy=1.3.0
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.29.0
  - tk=8.6.8
  - tornado=6.0.3
  - wheel=0.33.4
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - pillow==6.1.0
    - xlwt==1.3.0


